lock: false
setting:
  savePlayerData: true
  enableScript: false
  autoSave:
    enable: false
    time: 300000 # ms
  enablecCommands: true
  twitter:
    useTwitter: true
    consumerKey: ''
    consumerSecret: ''
