name: WhiteEggCore
version: 1.4
main: com.github.niwaniwa.we.core.WhiteEggCore
commands:
  whiteeggcore:
    description: admin command
    permission: whiteegg.moderator
    aliases: wbc
  toggle:
    aliases: to
    permission: whiteegg.core.command.toggle
  head:
  tweet:
    aliases: tw
    permission: whiteegg.core.command.twitter
  register:
    permission: whiteegg.core.command.twitter.register
  whisper:
    aliases: [tell, message, m, t, w]
    permission: whiteegg.core.command.whisper
  replay:
    aliases: [replay, r]
    permission: whiteegg.core.command.replay
  script:
permissions:
  whiteegg.*:
    description: Gives access to all WhiteEggPlugins
    children:
      whiteegg.core.*: true
      whiteegg.core.command.*: true
      whiteegg.core.command.toggle: true
      whiteegg.owner: true
      whiteegg.moderator: true
  whiteegg.core.*:
    description: Gives access to all WhiteEggCore
    children:
      whiteegg.core.command.*: true
      whiteegg.core.command.toggle: true
  whiteegg.core.command.*:
    description: Gives access to all WhiteEggCore commands
    children:
      whiteegg.core.command.toggle: true
  whiteegg.core.command.toggle:
    description: Gives access to all toggle command
    default: true
  whiteegg.owner:
    description: Owner permission
  whiteegg.moderator:
    description: Moderator permission
    children:
      whiteegg.core.command: true
